services:
  app:
    image: spring
    container_name: neversion-store
    ports:
    - "${PORT}:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_PORT: 8080